const QUESTION_DB = [
  // =========================
  // MUSIC (40)
  {
    id: "music-001",
    topic: "music",
    category: "Pop Culture",
    difficulty: "easy",
    question: "Which artist is known as the 'Queen of Pop'?",
    options: ["Madonna", "Adele", "Rihanna", "Lady Gaga"],
    correctAnswer: 0,
  },
  {
    id: "music-002",
    topic: "music",
    category: "Songs",
    difficulty: "easy",
    question: "‘Blinding Lights’ is a hit song by…",
    options: ["The Weeknd", "Drake", "Harry Styles", "Post Malone"],
    correctAnswer: 0,
  },
{
  id: "music-003",
  topic: "music",
  category: "BTS",
  difficulty: "easy",
  question: "What does BTS stand for (officially)?",
  options: [
    "Beyond the Stars",
    "Bangtan Sonyeondan",
    "Best Team Squad",
    "Boys That Sing"
  ],
  correctAnswer: 1,
},
  {
    id: "music-004",
    topic: "music",
    category: "Pop Culture",
    difficulty: "easy",
    question: "Taylor Swift fans are commonly called…",
    options: ["Swifties", "Beliebers", "Arianators", "Directioners"],
    correctAnswer: 0,
  },
{
  id: "music-005",
  topic: "music",
  category: "BLACKPINK",
  difficulty: "hard",
  question: "BLACKPINK debuted under which company?",
  options: ["SM Entertainment", "JYP Entertainment", "YG Entertainment", "HYBE"],
  correctAnswer: 2,
},
  {
    id: "music-006",
    topic: "music",
    category: "Hip Hop",
    difficulty: "easy",
    question: "Which rapper is known for 'God's Plan'?",
    options: ["Drake", "Kendrick Lamar", "Eminem", "Travis Scott"],
    correctAnswer: 0,
  },
{
  id: "music-007",
  topic: "music",
  category: "Billie Eilish",
  difficulty: "easy",
  question: "Billie Eilish became viral first with which song?",
  options: ["bad guy", "ocean eyes", "bury a friend", "when the party’s over"],
  correctAnswer: 1,
},
  {
    id: "music-008",
    topic: "music",
    category: "Icons",
    difficulty: "easy",
    question: "Which artist is called the 'King of Pop'?",
    options: ["Michael Jackson", "Elvis Presley", "Prince", "Justin Bieber"],
    correctAnswer: 0,
  },
{
  id: "music-009",
  topic: "music",
  category: "Adele",
  difficulty: "hard",
  question: "Adele won an Oscar for which James Bond theme?",
  options: ["Skyfall", "No Time to Die", "Writing’s on the Wall", "GoldenEye"],
  correctAnswer: 0,
},
{
  id: "music-010",
  topic: "music",
  category: "Lyrics",
  difficulty: "hard",
  question: "Which song includes the lyric: \"This is the end, Hold your breath and count to ten\"?",
  options: ["Rolling in the Deep", "Set Fire to the Rain", "Skyfall", "Rumour Has It"],
  correctAnswer: 2,
},
  {
    id: "music-011",
    topic: "music",
    category: "Artists",
    difficulty: "medium",
    question: "The Weeknd's real first name is…",
    options: ["Abel", "Noah", "Jacob", "Ethan"],
    correctAnswer: 0,
  },
  {
    id: "music-012",
    topic: "music",
    category: "K-Pop",
    difficulty: "medium",
    question: "Which BLACKPINK member released 'LALISA' as a solo?",
    options: ["Lisa", "Jennie", "Rosé", "Jisoo"],
    correctAnswer: 0,
  },
  {
    id: "music-013",
    topic: "music",
    category: "Pop Culture",
    difficulty: "hard",
    question: "Which Bad Bunny album title literally means 'A Summer Without You'?",
    options: [
      "Un Verano Sin Ti",
      "YHLQMDLG",
      "El Último Tour del Mundo",
      "X 100PRE",
    ],
    correctAnswer: 0,
  },
    {
    id: "music-014",
    topic: "music",
    category: "Albums",
    difficulty: "medium",
    question: "Which Billie Eilish album includes the era with the neon-green hair look?",
    options: [
      "When We All Fall Asleep, Where Do We Go?",
      "Happier Than Ever",
      "Ocean Eyes (EP)",
      "Folklore",
    ],
    correctAnswer: 0,
  },
    {
    id: "music-015",
    topic: "music",
    category: "Bands",
    difficulty: "easy",
    question: "‘Sweater Weather’ is a song by…",
    options: ["The Neighbourhood", "Arctic Monkeys", "Imagine Dragons", "OneRepublic"],
    correctAnswer: 0,
  },
  {
  id: "music-016",
  topic: "music",
  category: "Lyrics",
  difficulty: "hard",
  question: "Which Melanie song includes: \"Picture, picture, smile for the picture. Pose with your brother, won't you be a good sister?\"?",
  options: ["Cake", "Dollhouse", "Soap", "Pacify Her"],
  correctAnswer: 1,
},
{
  id: "music-017",
  topic: "music",
  category: "Justin Bieber",
  difficulty: "easy",
  question: "Justin Bieber first became famous mainly through…",
  options: ["A TV talent show", "YouTube covers", "A Disney series", "A rap battle"],
  correctAnswer: 1,
},
  {
    id: "music-018",
    topic: "music",
    category: "Pop",
    difficulty: "medium",
    question: "‘As It Was’ is by…",
    options: ["Harry Styles", "Shawn Mendes", "Ed Sheeran", "Charlie Puth"],
    correctAnswer: 0,
  },
   {
    id: "music-019",
    topic: "music",
    category: "Trivia",
    difficulty: "hard",
    question: "What is the meaning behind the name 'XXXTentacion' as he explained it?",
    options: [
      "A random gamer tag",
      "Symbolic of temptation and unknown",
      "A nickname from school",
      "Based on a movie character"
    ],
    correctAnswer: 1,
  },
 {
    id: "music-020",
    topic: "music",
    category: "Pop Culture",
    difficulty: "easy",
    question: "Lady Gaga’s real first name is…",
    options: ["Stefani", "Isabella", "Ariana", "Robyn"],
    correctAnswer: 0,
  },
  {
    id: "music-021",
    topic: "music",
    category: "Collabs",
    difficulty: "medium",
    question: "‘Señorita’ is a duet by Camila Cabello and…",
    options: ["Shawn Mendes", "Justin Bieber", "The Weeknd", "Zayn"],
    correctAnswer: 0,
  },
  {
    id: "music-022",
    topic: "music",
    category: "Pop Culture",
    difficulty: "medium",
    question: "Which singer is famous for the nickname 'Ari' among fans?",
    options: ["Ariana Grande", "Adele", "Lorde", "Shakira"],
    correctAnswer: 0,
  },
  {
    id: "music-023",
    topic: "music",
    category: "International",
    difficulty: "medium",
    question: "Which group is known for songs like 'Dynamite' and 'Butter'?",
    options: ["BTS", "TWICE", "SEVENTEEN", "ITZY"],
    correctAnswer: 0,
  },
{
    id: "music-024",
    topic: "music",
    category: "Lyrics",
    difficulty: "easy",
    question: 'Finish the lyric: "I\'m the bad guy, _____." (Billie Eilish)',
    options: ["duh", "yeah", "okay", "huh"],
    correctAnswer: 0,
  },
{
  id: "music-025",
  topic: "music",
  category: "Lyrics",
  difficulty: "medium",
  question: 'Which song includes: "Im sick and Im tired, too I can admit, I am not fireproof"?',
  options: ["Sweater Weather", "The Beach", "R.I.P. 2 My Youth", "Reflections"],
  correctAnswer: 1,
},
  {
    id: "music-026",
    topic: "music",
    category: "Awards",
    difficulty: "hard",
    question: "Which artist has the nickname 'Queen Bey'?",
    options: ["Beyoncé", "Nicki Minaj", "Rihanna", "Selena Gomez"],
    correctAnswer: 0,
  },

  {
    id: "music-028",
    topic: "music",
    category: "Rock/Alt",
    difficulty: "hard",
    question: "‘Smells Like Teen Spirit’ is by…",
    options: ["Nirvana", "Green Day", "Foo Fighters", "Linkin Park"],
    correctAnswer: 0,
  },
{
  id: "music-029",
  topic: "music",
  category: "Lyrics",
  difficulty: "medium",
  question: 'Which song includes: "Cause its too coldFor you here And now, so let me hold Both your hands in the holes of my sweater"?',
  options: ["Sweater Weather", "Softcore", "Daddy Issues", "Cry Baby"],
  correctAnswer: 0,
},
{
  id: "music-030",
  topic: "music",
  category: "Ren",
  difficulty: "easy",
  question: "Ren is widely known for which viral track that starts with him talking to himself?",
  options: ["Hi Ren", "Chalk Outlines", "Sick Boi", "Money Game Pt. 2"],
  correctAnswer: 0,
},
{
  id: "music-031",
  topic: "music",
  category: "Ren",
  difficulty: "medium",
  question: 'Which Ren song includes:"I feel like its not me, its the world thats sick Were given everything we need and we commoditize it" ?',
  options: ["Sick Boi", "The Hunger", "Hi Ren", "Jenny's Tale"],
  correctAnswer: 0,
},
  {
    id: "music-032",
    topic: "music",
    category: "Hip Hop",
    difficulty: "hard",
    question: "Which rapper is known for the alter-ego 'Slim Shady'?",
    options: ["Eminem", "Drake", "Kanye West", "J. Cole"],
    correctAnswer: 0,
  },
  {
    id: "music-033",
    topic: "music",
    category: "K-Pop",
    difficulty: "hard",
    question: "Which K-pop group has members like Bang Chan and Felix?",
    options: ["Stray Kids", "TXT", "ENHYPEN", "NCT 127"],
    correctAnswer: 0,
  },
{
  id: "music-034",
  topic: "music",
  category: "NF",
  difficulty: "hard",
  question: "NF is famous for *not* doing what in most of his songs?",
  options: ["Using profanity", "Rapping fast", "Making sad music", "Using orchestral beats"],
  correctAnswer: 0,
},
{
  id: "music-035",
  topic: "music",
  category: "Eminem",
  difficulty: "medium",
  question: "“Mockingbird” is mainly written as a message to…",
  options: ["his daughters", "his fans", "his hometown", "his younger self"],
  correctAnswer: 0,
},
  {
    id: "music-036",
    topic: "music",
    category: "Icons",
    difficulty: "hard",
    question: "Which artist is famous for the glove + moonwalk era?",
    options: ["Michael Jackson", "Prince", "Elton John", "Bruno Mars"],
    correctAnswer: 0,
  },
  {
    id: "music-037",
    topic: "music",
    category: "Festivals",
    difficulty: "hard",
    question: "Coachella is mostly known as a huge…",
    options: ["Music festival", "Movie award show", "Gaming tournament", "Fashion week"],
    correctAnswer: 0,
  },
{
  id: "music-038",
  topic: "music",
  category: "Tamino",
  difficulty: "easy",
  question: "Tamino is a singer-songwriter with Belgian and ___ roots.",
  options: ["Egyptian", "Mexican", "Japanese", "Brazilian"],
  correctAnswer: 0,
},
  {
    id: "music-039",
    topic: "music",
    category: "Trends",
    difficulty: "hard",
    question: "When a song 'charts' on Billboard, it means…",
    options: [
      "It ranks officially by popularity",
      "It gets removed from Spotify",
      "It becomes a meme instantly",
      "It only plays on radio",
    ],
    correctAnswer: 0,
  },
{
  id: "music-040",
  topic: "music",
  category: "Tamino",
  difficulty: "medium",
  question: 'Which Tamino song includes: "I have seen the worlds most beautiful places Still I feel, as If Im a walking machine" ?',
  options: ["Habibi", "Indigo Night", "Persephone", "Sunflower"],
  correctAnswer: 1,
},

  // =========================
  // MOVIES & SERIES (10)
  // =========================
  {
    id: "movies-001",
    topic: "movies-series",
    category: "Series - Stranger Things",
    difficulty: "easy",
    question: "In Stranger Things, what food is basically Eleven’s comfort-core personality?",
    options: ["Pizza", "Eggo waffles", "Ramen", "Tacos"],
    correctAnswer: 1,
  },
  {
    id: "movies-002",
    topic: "movies-series",
    category: "Series - Wednesday",
    difficulty: "easy",
    question: "Nevermore Academy in Wednesday is a school for…",
    options: ["Normal kids only", "Outcasts with powers", "Only rich celebrities", "Robots"],
    correctAnswer: 1,
  },
  {
    id: "movies-003",
    topic: "movies-series",
    category: "Movie - Harry Potter",
    difficulty: "easy",
    question: "In Harry Potter, which house was Harry sorted into?",
    options: ["Slytherin", "Ravenclaw", "Gryffindor", "Hufflepuff"],
    correctAnswer: 2,
  },
  {
    id: "movies-004",
    topic: "movies-series",
    category: "Anime - Jujutsu Kaisen",
    difficulty: "medium",
    question: "In Jujutsu Kaisen, Gojo Satoru is memed online as “perfect husband” mostly because of his…",
    options: ["Cooking skills", "Confidence + looks", "Being shy", "Love for homework"],
    correctAnswer: 1,
  },
  {
    id: "movies-005",
    topic: "movies-series",
    category: "Series - Stranger Things",
    difficulty: "medium",
    question: "Steve Harrington’s meme title in Stranger Things fandom is basically…",
    options: ["The villain", "Mom/Dad of the group", "Quiet nerd", "The teacher"],
    correctAnswer: 1,
  },
  {
    id: "movies-006",
    topic: "movies-series",
    category: "Series - Wednesday",
    difficulty: "medium",
    question: "In Wednesday, why did Wednesday get kicked out of her old school?",
    options: ["Failed exams", "Released piranhas", "Skipped class too much", "Stole test answers"],
    correctAnswer: 1,
  },
  {
    id: "movies-007",
    topic: "movies-series",
    category: "Movie - Harry Potter",
    difficulty: "medium",
    question: "In Harry Potter, what guards the entrance to Gryffindor girls’ dorm?",
    options: ["A troll", "A portrait that won’t open unless you’re a girl", "A dragon", "A talking hat"],
    correctAnswer: 1,
  },
  {
    id: "movies-008",
    topic: "movies-series",
    category: "Anime - Attack on Titan",
    difficulty: "easy",
    question: "In Attack on Titan, what are the huge enemies called?",
    options: ["Demons", "Titans", "Kaiju", "Giants of Light"],
    correctAnswer: 1,
  },
  {
    id: "movies-009",
    topic: "movies-series",
    category: "Series - Wednesday",
    difficulty: "easy",
    question: "Wednesday’s roommate Enid is basically…",
    options: ["Same vibe as Wednesday", "Sunshine opposite energy", "Villain arc", "Teacher mode"],
    correctAnswer: 1,
  },
  {
    id: "movies-010",
    topic: "movies-series",
    category: "Movie - Spider-Man (MCU)",
    difficulty: "easy",
    question: "In the MCU, Spider-Man under the mask is…",
    options: ["Peter Parker", "Tony Stark", "Bruce Wayne", "Clark Kent"],
    correctAnswer: 0,
  },

  {
    id: "movies-011",
    topic: "movies-series",
    category: "Anime - Demon Slayer",
    difficulty: "medium",
    question: "“NEZUKO-CHAAAAN!” screaming energy in Demon Slayer belongs to who?",
    options: ["Zenitsu", "Tanjiro", "Inosuke", "Giyu"],
    correctAnswer: 0,
  },
  {
    id: "movies-012",
    topic: "movies-series",
    category: "Series - Stranger Things",
    difficulty: "hard",
    question: "In Stranger Things S4, Max survives the iconic scene because…",
    options: ["She moved away", "Her favorite song pulls her back", "Vecna changes his mind", "Eleven time-travels"],
    correctAnswer: 1,
  },
  {
    id: "movies-013",
    topic: "movies-series",
    category: "Movie - Harry Potter",
    difficulty: "medium",
    question: "In Harry Potter, what does the Marauder’s Map show?",
    options: ["Only Hogwarts rules", "Live locations of everyone in Hogwarts", "Future spells", "Secret monsters only"],
    correctAnswer: 1,
  },
  {
    id: "movies-014",
    topic: "movies-series",
    category: "Anime - Jujutsu Kaisen",
    difficulty: "medium",
    question: "In JJK, Yuji Itadori becomes host for…",
    options: ["A phoenix", "Ryomen Sukuna", "A dragon spirit", "A cursed sword"],
    correctAnswer: 1,
  },
  {
    id: "movies-015",
    topic: "movies-series",
    category: "Series - Wednesday",
    difficulty: "medium",
    question: "Why did Wednesday’s dance go viral?",
    options: ["It was normal prom choreography", "It was chaotic gothic-weird in a good way", "TikTok paid promo", "She copied Enid"],
    correctAnswer: 1,
  },
  {
    id: "movies-016",
    topic: "movies-series",
    category: "Movie - Disney/Pixar",
    difficulty: "easy",
    question: "Which Pixar movie emotionally destroyed everyone with a floating house + balloons?",
    options: ["Up", "Inside Out", "Coco", "Wall-E"],
    correctAnswer: 0,
  },
  {
    id: "movies-017",
    topic: "movies-series",
    category: "Movie - Avengers",
    difficulty: "medium",
    question: "In Endgame, the “cinema screamed” moment was when…",
    options: ["Hulk danced", "Cap lifted Thor’s hammer", "Iron Man turned evil", "Thanos apologized"],
    correctAnswer: 1,
  },
  {
    id: "movies-018",
    topic: "movies-series",
    category: "Anime - Death Note",
    difficulty: "medium",
    question: "The Death Note works if Light…",
    options: ["Draws your face", "Writes your name while picturing you", "Says your name out loud", "Touches you"],
    correctAnswer: 1,
  },
  {
    id: "movies-019",
    topic: "movies-series",
    category: "Movie - Coraline",
    difficulty: "hard",
    question: "In Coraline, the Other Mother is terrifying mainly because of her…",
    options: ["Button eyes", "Blue hair", "Cute voice", "Pet cat"],
    correctAnswer: 0,
  },
  {
    id: "movies-020",
    topic: "movies-series",
    category: "Anime - Naruto",
    difficulty: "medium",
    question: "Sharingan is linked to which clan?",
    options: ["Hyuga", "Uchiha", "Nara", "Akimichi"],
    correctAnswer: 1,
  },

  {
    id: "movies-021",
    topic: "movies-series",
    category: "Series - The Boys",
    difficulty: "hard",
    question: "Homelander’s smile became a meme because it looked…",
    options: ["Cute and wholesome", "Terrifyingly fake", "Sleepy", "Confused"],
    correctAnswer: 1,
  },
  {
    id: "movies-022",
    topic: "movies-series",
    category: "Movie - Harry Potter",
    difficulty: "hard",
    question: "Who betrayed Lily & James to Voldemort?",
    options: ["Sirius Black", "Peter Pettigrew", "Remus Lupin", "Snape"],
    correctAnswer: 1,
  },
  {
    id: "movies-023",
    topic: "movies-series",
    category: "Series - Wednesday",
    difficulty: "hard",
    question: "Tyler is linked to the monster because he is…",
    options: ["A vampire", "A Hyde", "A werewolf", "A siren"],
    correctAnswer: 1,
  },
  {
    id: "movies-024",
    topic: "movies-series",
    category: "Anime - One Piece",
    difficulty: "easy",
    question: "Luffy’s dream is to become…",
    options: ["A navy admiral", "King of the Pirates", "A scientist", "A chef"],
    correctAnswer: 1,
  },
  {
    id: "movies-025",
    topic: "movies-series",
    category: "Anime - Your Name",
    difficulty: "medium",
    question: "Your Name hits hard because of…",
    options: ["Space war", "Body-swap + fate timing", "School exams", "Cooking battles"],
    correctAnswer: 1,
  },
  {
    id: "movies-026",
    topic: "movies-series",
    category: "Series - Stranger Things",
    difficulty: "medium",
    question: "The scary alternate dimension is called…",
    options: ["The Dark Zone", "The Upside Down", "The Nether", "The Backrooms"],
    correctAnswer: 1,
  },
  {
    id: "movies-027",
    topic: "movies-series",
    category: "Movie - Harry Potter",
    difficulty: "medium",
    question: "What sport do they play on broomsticks?",
    options: ["Quidditch", "Skyball", "Broom hockey", "Wizard racing"],
    correctAnswer: 0,
  },
  {
    id: "movies-028",
    topic: "movies-series",
    category: "Anime - Jujutsu Kaisen",
    difficulty: "hard",
    question: "Megumi’s main cursed technique summons…",
    options: ["Shikigami shadows", "Fire dragons", "Lightning swords", "Ice wolves only"],
    correctAnswer: 0,
  },
  {
    id: "movies-029",
    topic: "movies-series",
    category: "Movie - Joker",
    difficulty: "easy",
    question: "The stairs-dance meme comes from which character?",
    options: ["Batman", "Joker", "Deadpool", "Venom"],
    correctAnswer: 1,
  },
  {
    id: "movies-030",
    topic: "movies-series",
    category: "Anime - My Hero Academia",
    difficulty: "medium",
    question: "Deku’s power originally comes from…",
    options: ["Bakugo", "All Might", "Endeavor", "Aizawa"],
    correctAnswer: 1,
  },

  {
    id: "movies-031",
    topic: "movies-series",
    category: "Movie - Wall-E",
    difficulty: "medium",
    question: "Wall-E made everyone cry because he was basically…",
    options: ["A villain robot", "A lonely trash-collector with feelings", "A war machine", "A comedy sidekick"],
    correctAnswer: 1,
  },
  {
    id: "movies-032",
    topic: "movies-series",
    category: "Series - Arcane",
    difficulty: "medium",
    question: "Arcane’s ‘team Vi vs team Jinx’ drama exists because they are…",
    options: ["Random strangers", "Sisters with trauma", "Best friends only", "Teacher & student"],
    correctAnswer: 1,
  },
  {
    id: "movies-033",
    topic: "movies-series",
    category: "Anime - Tokyo Revengers",
    difficulty: "easy",
    question: "Takemichi’s main power is…",
    options: ["Time travel", "Mind reading", "Super strength", "Teleporting"],
    correctAnswer: 0,
  },
  {
    id: "movies-034",
    topic: "movies-series",
    category: "Series - K-Drama",
    difficulty: "medium",
    question: "The classic “fall + catch” scene usually means…",
    options: ["They’ll hate forever", "They’re about to fall in love", "Someone dies", "Final episode"],
    correctAnswer: 1,
  },
  {
    id: "movies-035",
    topic: "movies-series",
    category: "Anime - Attack on Titan",
    difficulty: "hard",
    question: "Levi is called the fandom’s ‘tired short king’ because he’s…",
    options: ["Lazy", "Overpowered but done with everyone’s nonsense", "Always smiling", "A clown"],
    correctAnswer: 1,
  },
  {
    id: "movies-036",
    topic: "movies-series",
    category: "Movie - Harry Potter",
    difficulty: "hard",
    question: "To defeat Voldemort fully, what must be destroyed?",
    options: ["The Elder Wand", "Horcruxes", "The Sorting Hat", "The Marauder’s Map"],
    correctAnswer: 1,
  },
  {
    id: "movies-037",
    topic: "movies-series",
    category: "Series - Wednesday",
    difficulty: "medium",
    question: "Wednesday’s pet scorpion is named…",
    options: ["Fluffy", "Nero", "Hector", "Bongo"],
    correctAnswer: 2,
  },
  {
    id: "movies-038",
    topic: "movies-series",
    category: "Anime - Jujutsu Kaisen",
    difficulty: "hard",
    question: "In JJK memes, who is the ultimate ‘walking red flag but we still stan’?",
    options: ["Mikasa", "Tanjiro", "Sukuna", "Deku"],
    correctAnswer: 2,
  },
  {
    id: "movies-039",
    topic: "movies-series",
    category: "Anime - Demon Slayer",
    difficulty: "medium",
    question: "In Demon Slayer, Inosuke is iconic because he fights wearing…",
    options: ["A fox mask", "A boar head mask", "A crow mask", "No mask ever"],
    correctAnswer: 1,
  },
  {
    id: "movies-040",
    topic: "movies-series",
    category: "Movie - Harry Potter",
    difficulty: "easy",
    question: "What is the name of Harry’s owl?",
    options: ["Errol", "Crookshanks", "Hedwig", "Scabbers"],
    correctAnswer: 2,
  },

  // ===== NEW ONES (Anne with an E / Peaky Blinders / Handmaid) =====

  {
    id: "movies-041",
    topic: "movies-series",
    category: "Series - Anne with an E",
    difficulty: "easy",
    question: "Anne in Anne with an E is obsessed with…",
    options: ["Being silent", "dramatic storytelling", "Sports only", "Math competitions"],
    correctAnswer: 1,
  },
  {
    id: "movies-042",
    topic: "movies-series",
    category: "Series - Anne with an E",
    difficulty: "medium",
    question: "Anne’s enemies to lovers arc is with…",
    options: ["Diana", "Ruby", "Rachel Lynde", "Gilbert"],
    correctAnswer: 3,
  },
  {
    id: "movies-043",
    topic: "movies-series",
    category: "Series - Peaky Blinders",
    difficulty: "easy",
    question: "Tommy Shelby is famous for always wearing…",
    options: ["A cowboy hat", "A flat cap", "A crown", "A hoodie"],
    correctAnswer: 1,
  },
  {
    id: "movies-044",
    topic: "movies-series",
    category: "Series - Peaky Blinders",
    difficulty: "medium",
    question: "The Peaky Blinders gang is based in…",
    options: ["London", "Birmingham", "New York", "Dublin"],
    correctAnswer: 1,
  },
  {
    id: "movies-045",
    topic: "movies-series",
    category: "Series - Peaky Blinders",
    difficulty: "hard",
    question: "What secret weapon is hidden in the Peaky Blinders cap (legendary detail)?",
    options: ["Coins", "Razor blades", "A tracking chip", "A ring"],
    correctAnswer: 1,
  },
  {
    id: "movies-046",
    topic: "movies-series",
    category: "Series - The Handmaid’s Tale",
    difficulty: "hard",
    question: "Handmaids wear red mainly because it symbolizes…",
    options: ["Royalty", "Fertility", "War power", "Luxury fashion"],
    correctAnswer: 1,
  },
  {
    id: "movies-047",
    topic: "movies-series",
    category: "Series - Anne with an E",
    difficulty: "hard",
    question: "Anne’s biggest life flex by the end is that she…",
    options: ["Leaves school forever", "Gets into Queen’s College", "Becomes mayor", "Moves to Paris"],
    correctAnswer: 1,
  },

  // =========================
  // MEMES & RIDDLES (10)
  // =========================
{
    id: "memes-001",
    topic: "memes-riddles",
    category: "Memes",
    difficulty: "easy",
    question: "When a meme is 'viral', it means…",
    options: [
      "It disappears fast",
      "It spreads quickly online",
      "It’s only for old people",
      "It’s always offensive",
    ],
    correctAnswer: 1,
  },
  {
    id: "memes-002",
    topic: "memes-riddles",
    category: "Internet Culture",
    difficulty: "medium",
    question: "If you 'DM' someone, you…",
    options: [
      "Block them",
      "Send a private message",
      "Tag them publicly",
      "Delete their account",
    ],
    correctAnswer: 1,
  },
  {
    id: "memes-003",
    topic: "memes-riddles",
    category: "Gen-Z Slang",
    difficulty: "medium",
    question: "Saying 'no cap' means…",
    options: ["No hat", "I’m not joking / for real", "I’m confused", "Stop talking"],
    correctAnswer: 1,
  },
  {
    id: "memes-004",
    topic: "memes-riddles",
    category: "Riddles",
    difficulty: "easy",
    question: "I speak without a mouth and hear without ears. What am I?",
    options: ["An echo", "A phone", "A shadow", "A cloud"],
    correctAnswer: 0,
  },
  {
    id: "memes-005",
    topic: "memes-riddles",
    category: "Riddles",
    difficulty: "easy",
    question: "What has to be broken before you can use it?",
    options: ["An egg", "A door", "A chair", "A phone"],
    correctAnswer: 0,
  },
  {
    id: "memes-006",
    topic: "memes-riddles",
    category: "Riddles",
    difficulty: "medium",
    question: "The more you take away from me, the bigger I get. What am I?",
    options: ["A hole", "A balloon", "A secret", "A wallet"],
    correctAnswer: 0,
  },
  {
    id: "memes-007",
    topic: "memes-riddles",
    category: "Gen-Z Slang",
    difficulty: "medium",
    question: "If something is 'sus', it is…",
    options: ["Suspicious", "Super cool", "Tiny", "Expensive"],
    correctAnswer: 0,
  },
  {
    id: "memes-008",
    topic: "memes-riddles",
    category: "Riddles",
    difficulty: "hard",
    question: "I’m full of keys but I can’t open any doors. What am I?",
    options: ["A keyboard", "A lock", "A map", "A suitcase"],
    correctAnswer: 0,
  },
  {
    id: "memes-009",
    topic: "memes-riddles",
    category: "Internet Culture",
    difficulty: "hard",
    question: "If a joke 'flops', it means…",
    options: ["Everyone laughs hard", "No one laughs", "It’s too smart", "It’s illegal"],
    correctAnswer: 1,
  },
  {
    id: "memes-010",
    topic: "memes-riddles",
    category: "Gen-Z Slang",
    difficulty: "easy",
    question: "When someone says you have 'rizz', they mean you…",
    options: ["Have good style", "Have charisma / flirting skill", "Are very rich", "Are super smart"],
    correctAnswer: 1,
  },
  {
    id: "memes-011",
    topic: "memes-riddles",
    category: "Memes",
    difficulty: "medium",
    question: "A meme that 'ages like milk' is one that…",
    options: ["Gets funnier over time", "Becomes cringe quickly", "Is always wholesome", "Never gets old"],
    correctAnswer: 1,
  },
  {
    id: "memes-012",
    topic: "memes-riddles",
    category: "Internet Culture",
    difficulty: "easy",
    question: "If you 'ratio' someone online, you…",
    options: ["Help them get likes", "Get more likes than their comment", "Delete your account", "Follow them"],
    correctAnswer: 1,
  },
  {
    id: "memes-013",
    topic: "memes-riddles",
    category: "Riddles",
    difficulty: "easy",
    question: "What has a head and a tail but no body?",
    options: ["A coin", "A snake", "A comet", "A shoe"],
    correctAnswer: 0,
  },
  {
    id: "memes-014",
    topic: "memes-riddles",
    category: "Riddles",
    difficulty: "medium",
    question: "What can run but never walks, has a mouth but never talks?",
    options: ["A river", "A dog", "A robot", "A clock"],
    correctAnswer: 0,
  },
  {
    id: "memes-015",
    topic: "memes-riddles",
    category: "Memes",
    difficulty: "hard",
    question: "A 'deep-fried meme' usually looks…",
    options: ["Super clean HD", "Over-edited, chaotic", "Like a documentary", "Like a cartoon only"],
    correctAnswer: 1,
  },
  {
    id: "memes-016",
    topic: "memes-riddles",
    category: "Gen-Z Slang",
    difficulty: "medium",
    question: "Saying someone is 'down bad' means they are…",
    options: ["Very sleepy", "Desperate", "Super successful", "Angry at everyone"],
    correctAnswer: 1,
  },
  {
    id: "memes-017",
    topic: "memes-riddles",
    category: "Gen-Z Slang",
    difficulty: "easy",
    question: "If someone says 'slay', they mean…",
    options: ["You did awesome", "You’re scary", "You’re lying", "Stop talking"],
    correctAnswer: 0,
  },
  {
    id: "memes-018",
    topic: "memes-riddles",
    category: "Riddles",
    difficulty: "hard",
    question: "I have cities but no houses, forests but no trees. What am I?",
    options: ["A map", "A dream", "A painting", "A computer"],
    correctAnswer: 0,
  },
  {
    id: "memes-019",
    topic: "memes-riddles",
    category: "Gen-Z Slang",
    difficulty: "hard",
    question: "If you say someone is 'giving NPC energy', you mean they…",
    options: ["Are super creative", "Act basic / scripted", "Are very athletic", "Are scary"],
    correctAnswer: 1,
  },
  {
    id: "memes-020",
    topic: "memes-riddles",
    category: "Riddles",
    difficulty: "medium",
    question: "What gets wetter the more it dries?",
    options: ["A towel", "A sponge", "Rain", "Snow"],
    correctAnswer: 0,
  },
  {
    id: "memes-021",
    topic: "memes-riddles",
    category: "Gen-Z Slang",
    difficulty: "easy",
    question: "If something is 'lowkey', it means…",
    options: ["Secretly", "Very loud", "Expensive", "Fake"],
    correctAnswer: 0,
  },
  {
    id: "memes-022",
    topic: "memes-riddles",
    category: "Gen-Z Slang",
    difficulty: "easy",
    question: "If something is 'highkey', it means…",
    options: ["Not important", "Very obvious", "Funny in a weird way", "Hidden"],
    correctAnswer: 1,
  },
  {
    id: "memes-023",
    topic: "memes-riddles",
    category: "Riddles",
    difficulty: "easy",
    question: "I’m tall when I’m young and short when I’m old. What am I?",
    options: ["A candle", "A lion", "A mountain", "A phone"],
    correctAnswer: 0,
  },
  {
    id: "memes-024",
    topic: "memes-riddles",
    category: "Gen-Z Slang",
    difficulty: "hard",
    question: "If someone is 'delulu', they are…",
    options: ["Super logical", "Delusional", "Angry", "Very shy"],
    correctAnswer: 1,
  },
    {
    id: "memes-025",
    topic: "memes-riddles",
    category: "Internet Culture",
    difficulty: "hard",
    question: "'Ragebait' content is made to…",
    options: [
      "Make people calm",
      "Get people angry on purpose for views",
      "Teach serious facts",
      "Be wholesome and cute"
    ],
    correctAnswer: 1,
  },

  // -------- Added requested slang --------
  {
    id: "memes-026",
    topic: "memes-riddles",
    category: "Gen-Z Slang",
    difficulty: "medium",
    question: "If someone calls you a 'simp', they mean you…",
    options: [
      "Are obsessed with someone",
      "Are super smart",
      "Don’t talk much",
      "Are always angry"
    ],
    correctAnswer: 0,
  },
  {
    id: "memes-027",
    topic: "memes-riddles",
    category: "Gen-Z Slang",
    difficulty: "medium",
    question: "If someone says 'I’m cooked', they mean…",
    options: [
      "They’re hungry",
      "They’re in trouble",
      "They’re winning",
      "They’re relaxing"
    ],
    correctAnswer: 1,
  },
  // =========================
  // LANGUAGE GENERAL KNOWLEDGE 
  // =========================
  {
    id: "langgen-001",
    topic: "language-general",
    category: "Grammar",
    difficulty: "medium",
    question: "Choose the correct sentence.",
    options: [
      "Neither of the answers are correct.",
      "Neither of the answers is correct.",
      "Neither answers is correct.",
      "Neither of answers are correct."
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-002",
    topic: "language-general",
    category: "Vocabulary",
    difficulty: "medium",
    question: "Which word is closest in meaning to 'inevitable'?",
    options: ["Avoidable", "Uncertain", "Unstoppable", "Temporary"],
    correctAnswer: 2,
  },
  {
    id: "langgen-003",
    topic: "language-general",
    category: "Idioms",
    difficulty: "medium",
    question: "What does 'once in a blue moon' mean?",
    options: ["Very rarely", "Every night", "At the wrong time", "In a loud way"],
    correctAnswer: 0,
  },
  {
    id: "langgen-004",
    topic: "language-general",
    category: "Grammar",
    difficulty: "hard",
    question: "Pick the correct option: 'No sooner _____ the train than it started to rain.'",
    options: ["we had boarded", "had we boarded", "we boarded", "did we board"],
    correctAnswer: 1,
  },
  {
    id: "langgen-005",
    topic: "language-general",
    category: "Vocabulary",
    difficulty: "medium",
    question: "Choose the best synonym for 'meticulous'.",
    options: ["Careless", "Detailed", "Fast", "Flexible"],
    correctAnswer: 1,
  },
  {
    id: "langgen-006",
    topic: "language-general",
    category: "Proverbs",
    difficulty: "medium",
    question: "‘Don’t count your chickens before they hatch’ means…",
    options: [
      "Don’t celebrate too early",
      "Don’t waste food",
      "Don’t trust people",
      "Don’t be lazy"
    ],
    correctAnswer: 0,
  },
  {
    id: "langgen-007",
    topic: "language-general",
    category: "Grammar",
    difficulty: "medium",
    question: "Choose the correct sentence.",
    options: [
      "If I will see her, I will tell her.",
      "If I see her, I will tell her.",
      "If I saw her, I will tell her.",
      "If I see her, I would tell her."
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-008",
    topic: "language-general",
    category: "Vocabulary",
    difficulty: "hard",
    question: "Which word best fits: 'His remarks were completely _____ and added no value.'",
    options: ["insightful", "redundant", "essential", "innovative"],
    correctAnswer: 1,
  },
  {
    id: "langgen-009",
    topic: "language-general",
    category: "Idioms",
    difficulty: "hard",
    question: "What does 'to play devil’s advocate' mean?",
    options: [
      "To support evil ideas",
      "To argue the opposite side to test reasoning",
      "To avoid conflict",
      "To agree with everyone"
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-010",
    topic: "language-general",
    category: "Grammar",
    difficulty: "hard",
    question: "Choose the correct option: 'The report, along with the charts, _____ on your desk.'",
    options: ["are", "were", "is", "have been"],
    correctAnswer: 2,
  },

  {
    id: "langgen-011",
    topic: "language-general",
    category: "Vocabulary",
    difficulty: "medium",
    question: "Pick the closest meaning to 'allocate'.",
    options: ["remove", "assign", "expand", "ignore"],
    correctAnswer: 1,
  },
  {
    id: "langgen-012",
    topic: "language-general",
    category: "Grammar",
    difficulty: "hard",
    question: "Which sentence uses the subjunctive correctly?",
    options: [
      "I wish he is here.",
      "I wish he were here.",
      "I wish he was here yesterday.",
      "I wish he will be here."
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-013",
    topic: "language-general",
    category: "Idioms",
    difficulty: "medium",
    question: "What does 'spill the beans' mean?",
    options: [
      "Cook badly",
      "Reveal a secret",
      "Make a mess",
      "Lose money"
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-014",
    topic: "language-general",
    category: "Vocabulary",
    difficulty: "hard",
    question: "Which word is the best antonym of 'scarce'?",
    options: ["rare", "limited", "abundant", "tiny"],
    correctAnswer: 2,
  },
  {
    id: "langgen-015",
    topic: "language-general",
    category: "Grammar",
    difficulty: "hard",
    question: "Choose the correct option: 'Hardly _____ finished speaking when the phone rang.'",
    options: ["had he", "he had", "has he", "he has"],
    correctAnswer: 0,
  },
  {
    id: "langgen-016",
    topic: "language-general",
    category: "Proverbs",
    difficulty: "hard",
    question: "‘A stitch in time saves nine’ suggests that…",
    options: [
      "Time heals everything",
      "Early action prevents bigger problems",
      "You should work slowly",
      "Small work is useless"
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-017",
    topic: "language-general",
    category: "Grammar",
    difficulty: "medium",
    question: "Choose the correct sentence.",
    options: [
      "She’s been working here since two years.",
      "She has been working here for two years.",
      "She is working here for two years.",
      "She works here since two years."
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-018",
    topic: "language-general",
    category: "Vocabulary",
    difficulty: "hard",
    question: "Which word best fits: 'The evidence was too _____ to ignore.'",
    options: ["vague", "compelling", "trivial", "random"],
    correctAnswer: 1,
  },
  {
    id: "langgen-019",
    topic: "language-general",
    category: "Idioms",
    difficulty: "hard",
    question: "What does 'to cut corners' mean?",
    options: [
      "To find a shortcut route",
      "To do something cheaply by skipping steps",
      "To improve quality",
      "To work overtime"
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-020",
    topic: "language-general",
    category: "Grammar",
    difficulty: "hard",
    question: "Choose the grammatically correct sentence.",
    options: [
      "The number of applicants are increasing.",
      "The number of applicants is increasing.",
      "A number of applicants is increasing.",
      "A number of applicants are increasing."
    ],
    correctAnswer: 1,
  },

  {
    id: "langgen-021",
    topic: "language-general",
    category: "Vocabulary",
    difficulty: "medium",
    question: "Pick the correct meaning of 'to implement'.",
    options: ["to postpone", "to carry out", "to remove", "to doubt"],
    correctAnswer: 1,
  },
  {
    id: "langgen-022",
    topic: "language-general",
    category: "Grammar",
    difficulty: "hard",
    question: "Choose the correct option: 'By next week, they _____ the project.'",
    options: ["finish", "will finish", "will have finished", "finished"],
    correctAnswer: 2,
  },
  {
    id: "langgen-023",
    topic: "language-general",
    category: "Idioms",
    difficulty: "medium",
    question: "What does 'to be on the same page' mean?",
    options: [
      "To read the same book",
      "To agree or share the same understanding",
      "To sit together",
      "To work in silence"
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-024",
    topic: "language-general",
    category: "Vocabulary",
    difficulty: "hard",
    question: "Which word best fits: 'Her explanation was _____ and confusing.'",
    options: ["coherent", "ambiguous", "clear", "precise"],
    correctAnswer: 1,
  },
  {
    id: "langgen-025",
    topic: "language-general",
    category: "Grammar",
    difficulty: "medium",
    question: "Choose the correct sentence.",
    options: [
      "I suggested him to rest.",
      "I suggested that he rest.",
      "I suggested that he rests.",
      "I suggested him resting."
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-026",
    topic: "language-general",
    category: "Proverbs",
    difficulty: "medium",
    question: "‘Practice makes perfect’ means…",
    options: [
      "Talent matters most",
      "Skill improves with repetition",
      "Perfection is impossible",
      "Learning is boring"
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-027",
    topic: "language-general",
    category: "Grammar",
    difficulty: "hard",
    question: "Pick the correct sentence.",
    options: [
      "Not only he was late, but also he forgot his notes.",
      "Not only was he late, but he also forgot his notes.",
      "Not only was he late, but also forgot his notes.",
      "Not only he was late, but he also forgot notes."
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-028",
    topic: "language-general",
    category: "Vocabulary",
    difficulty: "hard",
    question: "Pick the synonym of 'obsolete'.",
    options: ["modern", "outdated", "useful", "rare"],
    correctAnswer: 1,
  },
  {
    id: "langgen-029",
    topic: "language-general",
    category: "Idioms",
    difficulty: "hard",
    question: "What does 'to take something with a grain of salt' mean?",
    options: [
      "To believe it completely",
      "To be a bit skeptical",
      "To ignore it forever",
      "To write it down"
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-030",
    topic: "language-general",
    category: "Grammar",
    difficulty: "hard",
    question: "Choose the correct sentence.",
    options: [
      "The data was analyzed and show a trend.",
      "The data were analyzed and shows a trend.",
      "The data were analyzed and show a trend.",
      "The data was analyzed and shows a trend."
    ],
    correctAnswer: 2,
  },

  {
    id: "langgen-031",
    topic: "language-general",
    category: "Vocabulary",
    difficulty: "medium",
    question: "Which word best fits: 'The manager _____ a new policy last week.'",
    options: ["introduced", "invented", "refused", "ignored"],
    correctAnswer: 0,
  },
  {
    id: "langgen-032",
    topic: "language-general",
    category: "Grammar",
    difficulty: "hard",
    question: "Pick the correct option: 'If she _____ earlier, she wouldn’t have missed the bus.'",
    options: ["left", "had left", "would leave", "has left"],
    correctAnswer: 1,
  },
  {
    id: "langgen-033",
    topic: "language-general",
    category: "Idioms",
    difficulty: "medium",
    question: "What does 'to burn the midnight oil' mean?",
    options: [
      "To waste energy",
      "To work late into the night",
      "To fall asleep early",
      "To cook at night"
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-034",
    topic: "language-general",
    category: "Vocabulary",
    difficulty: "hard",
    question: "Which word best fits: 'His apology sounded _____ — like he didn’t mean it.'",
    options: ["sincere", "half-hearted", "emotional", "detailed"],
    correctAnswer: 1,
  },
  {
    id: "langgen-035",
    topic: "language-general",
    category: "Grammar",
    difficulty: "medium",
    question: "Choose the correct option: 'I’d rather you _____ here tomorrow.'",
    options: ["come", "came", "will come", "coming"],
    correctAnswer: 1,
  },
  {
    id: "langgen-036",
    topic: "language-general",
    category: "Proverbs",
    difficulty: "hard",
    question: "‘The early bird catches the worm’ suggests…",
    options: [
      "Wake up late",
      "Being early gives advantage",
      "Birds are lucky",
      "Work slowly"
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-037",
    topic: "language-general",
    category: "Grammar",
    difficulty: "hard",
    question: "Pick the correct sentence.",
    options: [
      "Had I known, I would tell you.",
      "Had I known, I would have told you.",
      "If I had known, I will tell you.",
      "If I know, I would have told you."
    ],
    correctAnswer: 1,
  },
  {
    id: "langgen-038",
    topic: "language-general",
    category: "Vocabulary",
    difficulty: "hard",
    question: "Choose the best synonym for 'to mitigate'.",
    options: ["to increase", "to reduce", "to ignore", "to explain"],
    correctAnswer: 1,
  },
  {
    id: "langgen-039",
    topic: "language-general",
    category: "Idioms",
    difficulty: "hard",
    question: "What does 'to jump the gun' mean?",
    options: [
      "To start too early",
      "To finish late",
      "To get distracted",
      "To avoid a task"
    ],
    correctAnswer: 0,
  },
  {
    id: "langgen-040",
    topic: "language-general",
    category: "Grammar",
    difficulty: "hard",
    question: "Choose the correct sentence.",
    options: [
      "This is the best movie I ever saw.",
      "This is the best movie I have ever seen.",
      "This is the best movie I am ever seeing.",
      "This was the best movie I have seen."
    ],
    correctAnswer: 1,
  },

]